### ISSUE TITLE
Non-deterministic error on tests.

### ISSUE THREAD

**Issue by autopawn** [ChileanVirtualObservatory/ACALIB#70]
`run_test.py` throws the following error sometimes:
```
======================================================================
FAIL: test_morph (core.test_analysis.TestAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/apawn/Documents/repos/acalib/testing/core/test_analysis.py", line 72, in test_morph
    np.testing.assert_almost_equal(boxing,result_boxing)
  File "/home/apawn/Music/miniconda3/envs/acalibenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 563, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/apawn/Music/miniconda3/envs/acalibenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/home/apawn/Music/miniconda3/envs/acalibenv/lib/python3.6/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 10.0%)
 x: array([  6.9413918e-310,   1.0000000e+000,   1.0000000e+000,
         1.0000000e+000,   1.0000000e+000,   1.0000000e+000,
         1.0000000e+000,   1.0000000e+000,   1.0000000e+000,
         8.4286332e+174])
 y: array([  6.9247206e-310,   1.0000000e+000,   1.0000000e+000,
         1.0000000e+000,   1.0000000e+000,   1.0000000e+000,
         1.0000000e+000,   1.0000000e+000,   1.0000000e+000,
         6.9246513e-310])
```

**Comment by maray** [comment]
I think the correct word is non-deterministic error...
